name: Netflix-App CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: netflix-app

jobs:
  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: Dockerfile

  build-and-push-image-to-dockerhub:
    name: Build & push image to Docker Hub
    needs: lint-dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - uses: actions/setup-node@v7
#        with:
#          node-version: 24
      - uses: docker/build-push-action@v7
        with:
          context: .
          build-args: |
            TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/netflix-app:latest

  build-and-push-image-to-github-registry:
    name: Push image to GitHub registry
    needs: lint-dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      - uses: actions/setup-node@v7
#        with:
#          node-version: 24
      - uses: docker/build-push-action@v7
        with:
          context: .
          build-args: |
            TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest